# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.OneToOneField(default='important', on_delete=django.db.models.deletion.CASCADE, to='courses.Description'),
            preserve_default=False,
        ),
    ]
